services:
  database:
    image: postgres:16-alpine
    container_name: planificador_viajes
    expose:
      - "5432"
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: